### ISSUE TITLE
ran blender/render_bodies.py, how to parse the generated output?

### ISSUE THREAD

**Issue by sabtorres** [lvzhaoyang/RefRESH#8]
Hello,
we're currently studying the code at my university's lab and we plan on using a subset of it to render a human body using blender with a given SH illumination (9 coefficients).

I managed to run the blender/render_bodies.py script (with some corrections here and there) and generated some output images (.png and .exr), using the same dataset as the authors (SURREAL). They're all black on sight, which probably means they just contain an intermediate data. Is there any way i can parse this type of data and display a final image?

Or instead, if the authors know a better way of rendering a human body SMPL model with precomputed radiance transfer (spherical harmonics lighting), we'd thank you for sharing it with us.

Best regards!

**Comment by sabtorres** [comment]
Actually, an image was generated in a "fg" directory, which was basically lots of men in underwear with a transparent background. Maybe this is all we need. If it's enough, I'll come back here later and close this issue. Thanks for patience.

**Comment by lvzhaoyang** [comment]
The foreground results are correct. I am not sure what the black images are. The whole image with the background is composited together using the background and foreground image rendered from the same viewpoint. 

You can load the background mesh first and then render both together. But it will be super super slow.

**Comment by sabtorres** [comment]
@lvzhaoyang got it. For my goals i only need the foreground image so that will be enough in the end. Thanks!
